SET TERM ^;
CREATE PROCEDURE P_PAGOS_CLIENTE(
    cliente_id INT
)
BEGIN
    SELECT P.NROPAGO, P.IMPORTE, P.NRO, F.FECHA
    FROM PAGO P
    JOIN FACTURA F ON P.NRO = F.NRO
    WHERE F.IDC = cliente_id;
END^
SET TERM ;^