-- Verificar que al crear un pago el importe sea mayor a 0
SET TERM ^;
CREATE TRIGGER TRG_PAGO_IMPORTE_VALIDO FOR PAGO ACTIVE
BEFORE INSERT POSITION 0
BEGIN
    
    IF(NEW.IMPORTE <= 0) THEN
        EXCEPTION PAGO_IMPORTE_INVALIDO;
    END IF;
    
END^
SET TERM ;^


-- Verificar que al crear un detalle la cantidad y el precio sea mayor que 0
SET TERM ^;
CREATE TRIGGER TRG_DETALLE_CANTIDAD_PRECIO_VALIDOS FOR DETALLE ACTIVE
BEFORE INSERT POSITION 0
BEGIN

    IF(NEW.CANT <= 0)THEN
        EXCEPTION DETALLE_CANTIDAD_INVALIDA;
    END IF;
    
    IF(NEW.PRECIO <= 0) THEN
        EXCEPTION DETALLE_PRECIO_INVALIDO;
    END IF;

END^
SET TERM ;^