-- Suponemos que un empleado puede ser un profesor o un preceptor, pero no ambos

CREATE TABLE PROFESOR
(
    ID INT NOT NULL,
    MATERIA VARCHAR(50),
    constraint PK_PROFESOR PRIMARY KEY (ID),
    CONSTRAINT FK_PROFESOR FOREIGN KEY (ID) REFERENCES EMPLEADO
);

CREATE TABLE PRECEPTOR
(
    ID INT NOT NULL,
    PRIMARIA_SECUNDARIA SMALLINT,
    -- 0 indica primaria y 1 secundaria
    constraint PK_PRECEPTOR PRIMARY KEY (ID),
    CONSTRAINT FK_PRECEPTOR FOREIGN KEY (ID) REFERENCES EMPLEADO
);

CREATE EXCEPTION EX_EMPLEADO 'Un empleado no puede ser un profesor y un preceptor a la vez';

SET TERM ^;

CREATE TRIGGER TRG_BI_PROFESOR FOR PROFESOR
ACTIVE BEFORE INSERT POSITION 0
AS 
begin
    IF (EXISTS (SELECT * FROM PRECEPTOR
        WHERE ID = NEW.ID)) then
        EXCEPTION EX_EMPLEADO;
END^

SET TERM ;^

SET TERM ^;

CREATE TRIGGER TRG_BI_PRECEPTOR FOR PRECEPTOR
ACTIVE BEFORE INSERT POSITION 0
AS 
begin
    IF (EXISTS (SELECT * FROM PROFESOR
        WHERE ID = NEW.ID)) then
        EXCEPTION EX_EMPLEADO;
END^

SET TERM ;^

-- Compruebo

INSERT INTO EMPLEADO (NOMBRE)
VALUES ('Margarita Lopez');
INSERT INTO EMPLEADO (NOMBRE)
VALUES ('Santiago de la Torre');

INSERT INTO PRECEPTOR (ID, PRIMARIA_SECUNDARIA)
VALUES (1, 0);

INSERT INTO PROFESOR (ID, MATERIA)
VALUES (1, 'Química');