CREATE TABLE EMPLEADO
(
    ID INT NOT NULL,
    NOMBRE VARCHAR(32),
    CONSTRAINT pk_empleado PRIMARY KEY (ID)
);

CREATE GENERATOR GEN_ID_EMPLEADO;
SET GENERATOR GEN_ID_EMPLEADO TO 0;

SET TERM ^;

CREATE TRIGGER TRG_BI_EMPLEADO FOR EMPLEADO
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    NEW.ID = GEN_ID(GEN_ID_EMPLEADO, 1);
END^

SET TERM ;^

-- Trigger antes de que se pretenda cambiar el ID del empleado

CREATE exception EX_ID_EMPLEADO 'No se puede cambiar el ID de un empleado.';

SET TERM ^;

CREATE TRIGGER TRG_BU_EMPLEADO FOR EMPLEADO
ACTIVE BEFORE UPDATE POSITION 0
AS
begin
    IF( NEW.ID <> OLD.ID) then
        EXCEPTION EX_ID_EMPLEADO;
END^

SET TERM ;^

-- Compruebo

INSERT INTO EMPLEADO (NOMBRE)
VALUES ('Maria Perez');
INSERT INTO EMPLEADO (NOMBRE)
VALUES ('Juan Duarte');

UPDATE EMPLEADO
SET ID = 3
WHERE ID = 1;