-- Un profesor/a puede tener como maximo dos aulas asignadas a él/ella

CREATE TABLE AULA
(
    COD_AULA INT NOT NULL,
    ID_PROF INT,
    CONSTRAINT PK_AULA PRIMARY KEY (COD_AULA),
    CONSTRAINT FK_ID_PROF FOREIGN KEY (ID_PROF) REFERENCES PROFESOR
);

CREATE EXCEPTION EX_AULA 'Un profesor no puede tener mas de dos aulas asignadas';

SET TERM ^;

CREATE TRIGGER TRG_BI_AULA FOR AULA
ACTIVE BEFORE INSERT POSITION 0
AS
begin
    IF((SELECT COUNT(*) FROM AULA
        WHERE ID_PROF = NEW.ID_PROF) >= 2) THEN
        EXCEPTION EX_AULA;
END^

SET TERM ;^

-- Compruebo

INSERT INTO PROFESOR
VALUES (3, 'Lengua');

INSERT INTO AULA (COD_AULA, ID_PROF)
VALUES (100, 3);
INSERT INTO AULA (COD_AULA, ID_PROF)
VALUES (102, 3);
INSERT INTO AULA (COD_AULA, ID_PROF)
VALUES (300, 3);

INSERT INTO PROFESOR (ID, MATERIA)
VALUES (4, 'Ciudadanía');
INSERT INTO AULA (COD_AULA, ID_PROF)
VALUES (300, 4);
