version: "3.8" # Versión de lenguaje de Docker compose
services: # Lista de contenedores que voy a levantar
  fb_maestro:
    image: jacobalberty/firebird:3.0 # Imágen oficial de FB. Una imágen es una plantilla read-only; el "plan"
    container_name: nodo_maestro
    ports:
      - "3051:3050" # Mapeo puertos de mi PC al contenedor
    environment: # Paso variables de config.
      - ISC_PASSWORD=masterkey # Contraseña de SYSDBA
    networks:
      - red_distribuida

  fb_espejo:
    image: jacobalberty/firebird:3.0
    container_name: nodo_espejo
    ports:
      - "3052:3050"
    environment: # Paso variables de config.
      - ISC_PASSWORD=masterkey # Contraseña de SYSDBA
    networks:
      - red_distribuida

networks: # A qué red virtual debe unirse?
  red_distribuida: # Nombre elegido para la red privada
    driver: bridge # El modo 'bridge' crea una red privada dentro de Docker permitiendo al nodo maestro hablar con el nodo espejo usando solo su nombre
