-- No permitir actualizar la tabla FACTURA
SET TERM ^;
CREATE TRIGGER TRG_FACTURA_NO_UPDATE FOR FACTURA ACTIVE
BEFORE UPDATE POSITION 0
BEGIN

    EXCEPTION FACTURA_NO_UPDATE;
    
END^
SET TERM ;^

-- No permitir actualizar la tabla PAGO
SET TERM ^;
CREATE TRIGGER TRG_PAGO_NO_UPDATE FOR PAGO ACTIVE
BEFORE UPDATE POSITION 0
BEGIN

    EXCEPTION PAGO_NO_UPDATE;
    
END^
SET TERM ;^